# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: lakefs-oss-contrib

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - make generate
    - make manifests

builds:
  - id: operator
    main: ./cmd/operator
    binary: lakefs-oss-contrib
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: authserver
    main: ./cmd/authserver
    binary: lakefs-auth-server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz

dockers:
  - id: operator-linux-amd64
    ids:
      - operator
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=BINARY=lakefs-oss-contrib"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - id: operator-linux-arm64
    ids:
      - operator
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg=BINARY=lakefs-oss-contrib"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name=lakefs-oss-contrib"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - id: authserver-linux-amd64
    ids:
      - authserver
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=BINARY=lakefs-auth-server"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name=lakefs-auth-server"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - id: authserver-linux-arm64
    ids:
      - authserver
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg=BINARY=lakefs-auth-server"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name=lakefs-auth-server"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

docker_manifests:
  - name_template: "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}"
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}-amd64"
      - "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/versioneer-tech/lakefs-oss-contrib:latest"
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}-amd64"
      - "ghcr.io/versioneer-tech/lakefs-oss-contrib:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}"
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}-amd64"
      - "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/versioneer-tech/lakefs-auth-server:latest"
    image_templates:
      - "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}-amd64"
      - "ghcr.io/versioneer-tech/lakefs-auth-server:{{ .Tag }}-arm64"
