# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: pkg.internal/v1beta1
kind: LakeFSCredential
metadata:
  labels:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/managed-by: kustomize
  name: admin-credentials
spec:
  userRef:
    name: admin-user
  accessKeyId: admin-access-key
  secretRef:
    name: admin-credentials
    key: secretAccessKey
---
apiVersion: pkg.internal/v1beta1
kind: LakeFSCredential
metadata:
  labels:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/managed-by: kustomize
  name: user-credentials
spec:
  userRef:
    name: user
  accessKeyId: user-access-key
  secretRef:
    name: user-credentials
    key: secretAccessKey
---
apiVersion: pkg.internal/v1beta1
kind: LakeFSCredential
metadata:
  labels:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/managed-by: kustomize
  name: readonly-user-credentials
spec:
  userRef:
    name: readonly-user
  accessKeyId: readonly-user-access-key
  secretRef:
    name: readonly-user-credentials
    key: secretAccessKey
