# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: pkg.internal/v1beta1
kind: LakeFSGCPolicy
metadata:
  labels:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/managed-by: kustomize
  name: default
spec:
  schedule: "0 3 * * *"
  retention:
    defaultRetentionDays: 14
