# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: pkg.internal/v1beta1
kind: LakeFSRole
metadata:
  labels:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/managed-by: kustomize
  name: viewer
spec:
  description: Viewer
  policies:
  - name: <REPOSITORY>-viewer
    statement:
    - effect: allow
      action:
      - fs:ListObjects
      - fs:ReadObject
      resource: arn:lakefs:fs:::repository/<REPOSITORY>
    - effect: allow
      action:
      - fs:ListObjects
      - fs:ReadObject
      resource: arn:lakefs:fs:::repository/<REPOSITORY>/branch/*
    - effect: allow
      action:
      - fs:ListObjects
      - fs:ReadObject
      resource: arn:lakefs:fs:::repository/<REPOSITORY>/object/*
    - effect: allow
      action:
      - fs:ListRepositories
      resource: "*"
