# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

resources:
- service_account.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: authserver
  newName: ghcr.io/versioneer-tech/lakefs-oss-contrib/auth-server
  newTag: latest
