# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/component: auth-server
    app.kubernetes.io/managed-by: kustomize
  name: auth-server
  namespace: system
spec:
  ports:
  - name: auth-http
    port: 80
    protocol: TCP
    targetPort: auth-http
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: lakefs-oss-contrib
    app.kubernetes.io/component: auth-server
