//go:build !ignore_autogenerated

// Copyright 2026, Versioneer (https://versioneer.at)
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSCredential) DeepCopyInto(out *LakeFSCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSCredential.
func (in *LakeFSCredential) DeepCopy() *LakeFSCredential {
	if in == nil {
		return nil
	}
	out := new(LakeFSCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSCredentialList) DeepCopyInto(out *LakeFSCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFSCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSCredentialList.
func (in *LakeFSCredentialList) DeepCopy() *LakeFSCredentialList {
	if in == nil {
		return nil
	}
	out := new(LakeFSCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSCredentialSpec) DeepCopyInto(out *LakeFSCredentialSpec) {
	*out = *in
	out.UserRef = in.UserRef
	out.SecretRef = in.SecretRef
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSCredentialSpec.
func (in *LakeFSCredentialSpec) DeepCopy() *LakeFSCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(LakeFSCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSCredentialStatus) DeepCopyInto(out *LakeFSCredentialStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSCredentialStatus.
func (in *LakeFSCredentialStatus) DeepCopy() *LakeFSCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFSCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSGroup) DeepCopyInto(out *LakeFSGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSGroup.
func (in *LakeFSGroup) DeepCopy() *LakeFSGroup {
	if in == nil {
		return nil
	}
	out := new(LakeFSGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSGroupList) DeepCopyInto(out *LakeFSGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFSGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSGroupList.
func (in *LakeFSGroupList) DeepCopy() *LakeFSGroupList {
	if in == nil {
		return nil
	}
	out := new(LakeFSGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSGroupSpec) DeepCopyInto(out *LakeFSGroupSpec) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]LakeFSUserReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSGroupSpec.
func (in *LakeFSGroupSpec) DeepCopy() *LakeFSGroupSpec {
	if in == nil {
		return nil
	}
	out := new(LakeFSGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSGroupStatus) DeepCopyInto(out *LakeFSGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSGroupStatus.
func (in *LakeFSGroupStatus) DeepCopy() *LakeFSGroupStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFSGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSPolicyStatement) DeepCopyInto(out *LakeFSPolicyStatement) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSPolicyStatement.
func (in *LakeFSPolicyStatement) DeepCopy() *LakeFSPolicyStatement {
	if in == nil {
		return nil
	}
	out := new(LakeFSPolicyStatement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSPolicyTemplate) DeepCopyInto(out *LakeFSPolicyTemplate) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]LakeFSPolicyStatement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSPolicyTemplate.
func (in *LakeFSPolicyTemplate) DeepCopy() *LakeFSPolicyTemplate {
	if in == nil {
		return nil
	}
	out := new(LakeFSPolicyTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRepository) DeepCopyInto(out *LakeFSRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRepository.
func (in *LakeFSRepository) DeepCopy() *LakeFSRepository {
	if in == nil {
		return nil
	}
	out := new(LakeFSRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRepositoryCredentialSecretReference) DeepCopyInto(out *LakeFSRepositoryCredentialSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRepositoryCredentialSecretReference.
func (in *LakeFSRepositoryCredentialSecretReference) DeepCopy() *LakeFSRepositoryCredentialSecretReference {
	if in == nil {
		return nil
	}
	out := new(LakeFSRepositoryCredentialSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRepositoryList) DeepCopyInto(out *LakeFSRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFSRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRepositoryList.
func (in *LakeFSRepositoryList) DeepCopy() *LakeFSRepositoryList {
	if in == nil {
		return nil
	}
	out := new(LakeFSRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRepositorySpec) DeepCopyInto(out *LakeFSRepositorySpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRepositorySpec.
func (in *LakeFSRepositorySpec) DeepCopy() *LakeFSRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(LakeFSRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRepositoryStatus) DeepCopyInto(out *LakeFSRepositoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRepositoryStatus.
func (in *LakeFSRepositoryStatus) DeepCopy() *LakeFSRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFSRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRole) DeepCopyInto(out *LakeFSRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRole.
func (in *LakeFSRole) DeepCopy() *LakeFSRole {
	if in == nil {
		return nil
	}
	out := new(LakeFSRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleBinding) DeepCopyInto(out *LakeFSRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleBinding.
func (in *LakeFSRoleBinding) DeepCopy() *LakeFSRoleBinding {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleBindingList) DeepCopyInto(out *LakeFSRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFSRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleBindingList.
func (in *LakeFSRoleBindingList) DeepCopy() *LakeFSRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleBindingSpec) DeepCopyInto(out *LakeFSRoleBindingSpec) {
	*out = *in
	out.Subject = in.Subject
	out.RoleRef = in.RoleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleBindingSpec.
func (in *LakeFSRoleBindingSpec) DeepCopy() *LakeFSRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleBindingStatus) DeepCopyInto(out *LakeFSRoleBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleBindingStatus.
func (in *LakeFSRoleBindingStatus) DeepCopy() *LakeFSRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleBindingSubject) DeepCopyInto(out *LakeFSRoleBindingSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleBindingSubject.
func (in *LakeFSRoleBindingSubject) DeepCopy() *LakeFSRoleBindingSubject {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleBindingSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleList) DeepCopyInto(out *LakeFSRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFSRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleList.
func (in *LakeFSRoleList) DeepCopy() *LakeFSRoleList {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleReference) DeepCopyInto(out *LakeFSRoleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleReference.
func (in *LakeFSRoleReference) DeepCopy() *LakeFSRoleReference {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleSpec) DeepCopyInto(out *LakeFSRoleSpec) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]LakeFSPolicyTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleSpec.
func (in *LakeFSRoleSpec) DeepCopy() *LakeFSRoleSpec {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSRoleStatus) DeepCopyInto(out *LakeFSRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSRoleStatus.
func (in *LakeFSRoleStatus) DeepCopy() *LakeFSRoleStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFSRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSSecretReference) DeepCopyInto(out *LakeFSSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSSecretReference.
func (in *LakeFSSecretReference) DeepCopy() *LakeFSSecretReference {
	if in == nil {
		return nil
	}
	out := new(LakeFSSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSUser) DeepCopyInto(out *LakeFSUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSUser.
func (in *LakeFSUser) DeepCopy() *LakeFSUser {
	if in == nil {
		return nil
	}
	out := new(LakeFSUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSUserList) DeepCopyInto(out *LakeFSUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LakeFSUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSUserList.
func (in *LakeFSUserList) DeepCopy() *LakeFSUserList {
	if in == nil {
		return nil
	}
	out := new(LakeFSUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakeFSUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSUserReference) DeepCopyInto(out *LakeFSUserReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSUserReference.
func (in *LakeFSUserReference) DeepCopy() *LakeFSUserReference {
	if in == nil {
		return nil
	}
	out := new(LakeFSUserReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSUserSpec) DeepCopyInto(out *LakeFSUserSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSUserSpec.
func (in *LakeFSUserSpec) DeepCopy() *LakeFSUserSpec {
	if in == nil {
		return nil
	}
	out := new(LakeFSUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakeFSUserStatus) DeepCopyInto(out *LakeFSUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakeFSUserStatus.
func (in *LakeFSUserStatus) DeepCopy() *LakeFSUserStatus {
	if in == nil {
		return nil
	}
	out := new(LakeFSUserStatus)
	in.DeepCopyInto(out)
	return out
}
