# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/pkg.internal_lakefsusers.yaml
- bases/pkg.internal_lakefsgroups.yaml
- bases/pkg.internal_lakefscredentials.yaml
- bases/pkg.internal_lakefsroles.yaml
- bases/pkg.internal_lakefsrolebindings.yaml
- bases/pkg.internal_lakefsrepositories.yaml
# +kubebuilder:scaffold:crdkustomizeresource
